---
title: Laravel Spin Template from WebJackl
authors:
  - Jigar Dhulla
description: Laravel template with MySQL database, Queue and Scheduler support. A middle-ground between basic and pro.
repository: https://github.com/webjackl/spin-template-laravel
issues: https://github.com/webjackl/spin-template-laravel/issues